application: gae-gitkit
version: test
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /
  script: main.app
  
- url: /callback
  script: gitkit.app
  
- url: /login
  script: gitkit.app
  
- url: /legacylogin
  script: gitkit.app  
  
- url: /logout
  script: gitkit.app
  
- url: /status
  script: gitkit.app

- url: /signup
  script: gitkit.app
  
- url: /_ah/xrds

  script: gitkit.app

libraries:
- name: webapp2
  version: "2.5.1"

